### ISSUE TITLE
打包之后项目无法正常使用

### ISSUE THREAD

**Issue by tuzixiangs** [neohan666/react-router-waiter#2]
vendor.0116ddd9.js:32 
        
       TypeError: l is not a function
    at s (VllageCollectiveHome.be4f0cc5.js:1:687)
    at v (VllageCollectiveHome.be4f0cc5.js:1:1153)
    at jf (vendor.0116ddd9.js:30:53005)
    at fc (vendor.0116ddd9.js:30:62500)
    at Ly (vendor.0116ddd9.js:34:9368)
    at My (vendor.0116ddd9.js:34:947)
    at $w (vendor.0116ddd9.js:34:875)
    at Ao (vendor.0116ddd9.js:34:730)
    at Ec (vendor.0116ddd9.js:32:10886)
    at vendor.0116ddd9.js:30:38809
hc @ vendor.0116ddd9.js:32
vendor.0116ddd9.js:30 
        
       Uncaught TypeError: l is not a function
    at s (VllageCollectiveHome.be4f0cc5.js:1:687)
    at v (VllageCollectiveHome.be4f0cc5.js:1:1153)
    at jf (vendor.0116ddd9.js:30:53005)
    at fc (vendor.0116ddd9.js:30:62500)
    at Ly (vendor.0116ddd9.js:34:9368)
    at My (vendor.0116ddd9.js:34:947)
    at $w (vendor.0116ddd9.js:34:875)
    at Ao (vendor.0116ddd9.js:34:730)
    at Ec (vendor.0116ddd9.js:32:10886)
    at vendor.0116ddd9.js:30:38809

**Comment by neohan666** [comment]
哪个版本，需要更详细的信息

**Comment by tuzixiangs** [comment]
> 哪个版本，需要更详细的信息

就是最新的版本,打包之后跑不起来

**Comment by neohan666** [comment]
> 

我这边无法复现

**Comment by neohan666** [comment]
> > 哪个版本，需要更详细的信息
> 
> 就是最新的版本,打包之后跑不起来

我这边复现不出

**Comment by neohan666** [comment]
从报错信息看，不像是插件原因，请检查下VllageCollectiveHome这个组件
